language: python
python:
  - "3.4"   # working version
  - "3.6"
env:
#  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.10.2   # working version
install:
  # Build/test dependencies
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt
before_script:
  # no for now
script:
  # init for migrations
  - python manage.py init -p 123456 -t
  # Normal tests
  - python manage.py test
